import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

final List DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Foot orthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c2',
    title: 'Ankle orthoses',
    color: Colors.white,
  ),
  Category(
    id: 'c3',
    title: 'knee orthoses',
    color: Colors.white,
  ),
  Category(
    id: 'c4',
    title: 'Hip orthoses',
    color: Colors.white,
  ),
  Category(
    id: 'c5',
    title: 'cervical orthoses',
    color: Colors.white,
  ),
  Category(
    id: 'c6',
    title: 'Cervicothoracic orthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c7',
    title: 'thoracolumbar orthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c8',
    title: 'Lumbosacralorthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c9',
    title: 'Sacroiliac orthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c10',
    title: 'Cervicothoracolumbosacralorthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c11',
    title: 'ThoracolumbosacralOrthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c12',
    title: 'shoulder orthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c13',
    title: 'Elbow joint orthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c14',
    title: 'wrist orthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c15',
    title: 'Thumb orthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c16',
    title: 'PIP joint orthosis',
    color: Colors.white,
  ),
  Category(
    id: 'c17',
    title: 'DIP jointorthosis',
    color: Colors.white,
  ),

];

final List DUMMY_MEALS = [
  Meal(
      id: 'm1',
      categories: [
        'c1',
      ],
      title: 'foot orthoses (FO)',
      imageUrl: 'assets/images/m1.png',
      steps: [
        'are like the tires on an automobile. They provide a critical, biomechanical contact point for the human body, and they can be helpful to correct problems in the foot, knee, hip, and spine',
        'Clinical Uses',
        'The uses of orthoses vary from pain relief, comfort and enhancement of performance.',
        'They are widely used in the treatment of different foot conditions:',
        'a)	Plantar Heel Pain',
        'b)	Patellofemoral Pain Syndrome',
        'c)	Tibialis Posterior Tendon Dysfunction',
        'd)	Peroneal Tendon Dysfunction',
        'e)	Midfoot Osteoarthritis',
        'f)	sesamoid problems',
        'g)	Plantar Plate Injury',
      ],
      videoUrl: 'https://youtu.be/3M66ydoaYJk'),
  Meal(
      id: 'm2',
      categories: [
        'c2',
      ],
      title: 'Solid/Rigid Ankle Foot Orthosis',
      imageUrl: 'assets/images/m2.png',
      steps: [
        'These are designed to control the foot and ankle at an appropriate angle and provide support in multiple different planes. We can also gain control at the knee by influencing the ankle and a solid AFO is sometimes suitable for this',
        'INDICATIONS',
        'a) foot drop',
        'b)	ankle mediolateral instability',
        'c)	  spasticity',
        'd)	 plantarflexion contracture',
        'e)	contracture prevention',
        'f)	 knee hyperextension',
        'g)	arthritic pain management',
        'Contraindications',
        'a)	Blocks range of motion.  Therefore, may be excessive if orthotic objective does not require blocking plantarflexion, dorsiflexion, and inversion/eversion.',
        'b)	Slows down forward progression.',
        'c)	Knee flexion/foot flat moment produced at heel strike/Perry’s first rocker.',
        'd)	Fair quadriceps strength is required if set in dorsiflexion',
      ],
      videoUrl: 'https://youtu.be/cPCqTrLKMO4'),
  Meal(
      id: 'm3',
      categories: [
        'c2',
      ],
      title: 'The floor-reaction ankle-foot orthosis',
      imageUrl: 'assets/images/m3.png',
      steps: [
        'is commonly prescribed for children with cerebral palsy who walk with excessive ankle dorsiflexion and excessive knee flexion during the stance phase of gait',
        'Indications',
        'a)	Adult Acquired Flatfoot',
        'b)	Posterior Tibial Tendon Dysfunction (PTTD)',
        'c)	Achilles Tendonitis',
        'd)	Osteoarthritis',
        'e)	Spina Bifida',
        'f)	Cerebral Palsy',
        'g)	Brain injuries',
        'h)	Spinal cord injuries',
        'i)	Post-polio paralysis',
      ],
      videoUrl: 'https://youtu.be/cPCqTrLKMO4'),
  Meal(
      id: 'm4',
      categories: [
        'c2',
      ],
      title: 'Weight-Relieving Ankle-Foot Orthoses',
      imageUrl: 'assets/images/m4.png',
      steps: [
        'This orthoses is also known as patellar tendon -bearing Ankle-Foot orthosis. It relives the weight bearing stress on the skeletal structures by taking the weight of limb through the solid ankle-foot orthoses or double upright. it transmits the force from knee through patellar tendon through the uprights and shoe to the ground. cuff should be in 10° dorsiflexion but best results are achieved with fixed ankle.',
        'INDICATION:',
        'Postoperative fusion about ankle, fracture of calcaneum, painful condition of heel, delayed non-union fracture of tibia, avascular necrosis of body of talus, sever degenerative arthritis of ankle and subtalar joints, osteomyelitis of calcaneum, Diabetic ulceration foot, chronic and painful conditions that are not amenable to surgery and sciatic nerve injury with insensitive sole of foot. ',
      ],
      videoUrl: 'https://youtu.be/RLnPSUi5aWM'),
  Meal(
    id: 'm5',
    categories: [
      'c2',
    ],
    title: 'Posterior Loaf Spring ankle foot orthoses',
    imageUrl: 'assets/images/m5.png',
    steps: [
      'It is used to prevent excessive equinus or drop foot in swing. It support the weight of the foot during swing phase as a means of enhancing swing limb swing clearance. Asist with controlled lowering of the foot during loading response in stance for patient with dorsiflexion weakness',
    ],
    videoUrl: 'https://youtu.be/-313of5-Ygo',
  ),
  Meal(
    id: 'm6',
    categories: [
      'c2',
    ],
    title: 'Articulated ankle foot orthosis',
    imageUrl: 'assets/images/m6.png',
    steps: [
      'It allows anatomical ankle to move through a specific ROM. It is used for foot drop, knee instability, lower limb weakness and mediolateral instability of the ankle',
    ],
    videoUrl: 'https://youtu.be/L464suY3pfU',
  ),
  Meal(
      id: 'm7',
      categories: [
        'c3',
      ],
      title: 'Custom knee brace',
      imageUrl: 'assets/images/m7.png',
      steps: [
        'They are prophylactic knee braces They are designed to mitigate or prevent soft tissue structures of the knee from contact or noncontact injuries. Supporting the ligaments that stabilize the knee joint. Limit tibial translation and rotation of the knee joint (ACL /PCL injury).  Off load the knee joint (meniscus injury / OA). Available for post. operative recovery, knee instabilities, osteoarthritis, ligaments stabilization, and for prevention of further injury',
      ],
      videoUrl: 'https://youtu.be/GoS5Bc6skOQ'),
  Meal(
    id: 'm8',
    categories: [
      'c3',
    ],
    title: 'Functional knee brace',
    imageUrl: 'assets/images/m8.png',
    steps: [
      'They are designed for individuals who have ligamentous instability. Provide external support that would limit the same knee motion as the ligament to prevent further instability. They also serve a rehabilitative function, as seen with the patients who have suffered anterior cruciate ligament (ACL) rupture and have undergone surgical repair to protect surgical repair. Ensure natural range of motion and prevent unnatural movement of the knee. Decrease the force of impact being applied to the knee during strenuous physical activities. Can help lessen pain and discomfort of the joints.',
    ],
    videoUrl: 'https://youtu.be/izGtlPg8UCE',
  ),
  Meal(
    id: 'm9',
    categories: [
      'c3',
    ],
    title: 'Post operative knee brace',
    imageUrl: 'assets/images/m9.png',
    steps: [
      'A unique and versatile, universal orthosis covers a large variety of leg lengths and widths.',
      '•With its extendable aluminum bars and cuffs, the brace can be made extremely short (45 cm) or long (60 cm).',
      '•Easy circumference adjustment from quite small to XX-Large.',
      '•After first installation remove “pull straps” so that straps attach to hook parts.',
      '•Hook pieces on the plastic cuff, hold the circumferential straps in place.',
      '•The stays remain in their position for easy re-application.',
      '•Foam pads with anti-slip surface hold the brace well in place.',
      '•Improved skin aeration due to limited skin coverage by the foam padding.',
      '•Convenient click closure system facilitate removal and re-application without having to reset for each application.',
      '•Additional foam pads can be applied for comfort and stability at the backside of the soft thigh straps.',
      '•Knee ROM easy to adjust or lock with dual system',
      '•Determine ROM restriction by changing position of press buttons on hinge dial.',
      '•Prevent patient from manipulating ROM with “lock caps” attached on press buttons.',
      '•Option to lock extra in 4 positions “0° – 15° – 30° – 45°”.',
    ],
    videoUrl: 'https://youtu.be/Pvk04jMiAho',
  ),
  Meal(
    id: 'm10',
    categories: [
      'c3',
    ],
    title: 'Neoprene knee braces',
    imageUrl: 'assets/images/m10.png',
    steps: [
      'Neoprene knee braces are one of the most popular types of knee brace on the market.',
      'Like all braces they provide good support to the knee joint reducing pain and instability.',
      'The added advantage of the neoprene material is that it retains heat, which helps promote healing and reduces swelling and pain.',
      'Neoprene is the best material out there at retaining heat and insulating. Neoprene is made from synthetic rubber and is commonly used in wetsuits. It works by preventing heat from escaping, thus trapping the heat next to your body, even during periods of inactivity. This increases the blood flow to the knee which promotes healing. ',
    ],
    videoUrl: 'https://youtu.be/aPJy3fp4-zs',
  ),
  Meal(
    id: 'm11',
    categories: [
      'c3',
    ],
    title: 'Patellar strap',
    imageUrl: 'assets/images/m11.png',
    steps: [
      "knee strap reduces pain caused by patellar tendonitis (jumpers' knee), Osgood Schlatter's, Chondromalacia Patella, and Runners Knee. It is also good for general anterior knee pain around the kneecap.",
      'It reduces forces going through the patella tendon due to a unique tubular buttress which applies constant, mild compression on the patellar tendon. It is perfect for people who do lots of running and/or jumping. Wrapping this simple band just below your knee reduces strain on the hard-working tendon connecting your patella (kneecap) and tibia (shinbone). It offers just enough support and stability to ease pain that may pop up during physical activity ',
      'The adjustable band applies just enough pressure on the patellar tendon to better align it with your kneecap. It changes both the direction and magnitude of the force on the knee while also providing stability.',
    ],
    videoUrl: 'https://youtu.be/CqIUyZfjRPA',
  ),
  Meal(
    id: 'm12',
    categories: [
      'c3',
    ],
    title: 'Unlocked single axis knee joint ',
    imageUrl: 'assets/images/m12.png',
    steps: [
      'Unlocked single axis knee joint ',
      'These joints have the ability to provide full flexion of the knee during the swing phase so the patients can walk with less effort and a more symmetrical gait pattern than the locked single axis knee joints.',
      'Indication',
      "1) Patients have weakness of lower limbs (drop foot with genu recurvatum) and can't use AFOs because they will increase the genu recurvatum",
      "2) Patients have weakness of lower limbs (drop foot with valgus and varus deformities) and can't use AFOs because they will increase the valgus and varus deformities",
      '3) Patients with LMNLs such as poliomyelitis. They are at risk of falling.',
      "4) Patients have quadriceps strength 3 or more.",
    ],
    videoUrl: 'https://youtu.be/dQgwta22gB8',
  ),
  Meal(
    id: 'm13',
    categories: [
      'c3',
    ],
    title: 'Single axis locking knee brace',
    imageUrl: 'assets/images/m13.png',
    steps: [
      "These joints don't allow knee flexion during the swing phase so the patients walk with more effort than unlocking single axis knee joints and asymmetrical gait pattern.",
      'Indications',
      '1)	Insufficient knee joint strength caused by stroke hemiplegia.',
      '2)	Pediatric numbness, lack of strength of lower limbs, joints cannot bear weight.',
      '3)	Patients with paraplegia, weakness of lower limbs.',
      '4)	Paraplegic patients (patients with complete paraplegia or partial high incomplete paraplegia at or below T10) caused by various reasons, to assist paraplegic patients to achieve the goal of practical independent walking, and to maximize the desire of paraplegic patients to take care of themselves.',
      "5)	patients have quadriceps strength less than 3 on oxford scale because they can't keep their knee in extension and support their body weight during gait.",
      'The most commonly used locking mechanisms are pawl locking with bail release and drop ring lock joint.'
          'Pawl locking has bail attached pasteriorly. It can unlock joints by pulling up to sit down in a chair',
      'Drop ring lock joint has ring. It can unlock joints by pulling up to sit in a chair',
    ],
    videoUrl: 'https://youtu.be/n4GwGEVIekc',
  ),
  Meal(
    id: 'm34',
    categories: [
      'c3',
    ],
    title: 'offset knee joint',
    imageUrl: 'assets/images/m34.png',
    steps: [
      'posteriorly offset, free knee',
      'Indications-:',
      'effective with patients of lower motor neuron diseases as poliomyelitis.',
      'patients with low thoracic upper lumbar spinal cord injuries.',
      'mechanism-: ',
      'the offset joint is aligned with its axis posterior to the axis of the anatomic knee.',
      'during stance the ground reaction passes nearer to the axis of the orthotic joint.',
      'so reduces the magnitude of external flexion moment that is acting to flex the limb. with forward progression the GRF moves anterior to the offset joint creating an extensor force that augment stance phase stability during single limb support.',
      'reduce problems of transition between sitting and standing if knee does not have to be unlocked.',
      'precautions-:',
      'if patient stand for long periods of time or walk on uneven surfaces the efficacy is reduced and may need locking mechanism for additional stability.',
      'the posterior offset knee joint should have a hyperextension stop to help prevent genu recurvatum.',
    ],
    videoUrl: 'https://youtu.be/HeMuAITnf_I',
  ),
  Meal(
    id: 'm14',
    categories: [
      'c3',
    ],
    title: 'The variable position locking orthotic knee joint',
    imageUrl: 'assets/images/m14.png',
    steps: [
      'dial lock, adjustable locking knee joint, serrated knee lock',
      'Indications-:',
      '-is used for those who are unable to fully extend the knee during stance because of knee flexion contracture.',
      'mechanism-: ',
      '-When there is a knee flexion contracture of more than 10 degrees, the GRF remains posterior to the anatomic knee joint during all of stance phase, and it becomes significantly more difficult for those with weakness or motor control impairment to generate the necessary muscle force for stance stability.',
      '-For these individuals, the variable position knee joint is locked in the most extended position possible providing an external mechanical stability.',
    ],
    videoUrl: 'https://youtu.be/HeMuAITnf_I',
  ),
  Meal(
    id: 'm15',
    categories: [
      'c3',
    ],
    title: 'Becker UTX ',
    imageUrl: 'assets/images/m15.png',
    steps: [
      'mechanical stance control knee-ankle foot orthosis.',
      'Most prescription guidelines for SC-KAFO:',
      'indicate that the individual must demonstrate muscle strength of at least 3 of 5 on manual muscle testing at hip extensors and flexors and full extension of the anatomic knee joint ',
      'Contraindications:',
      'for SC-kAFO use include fixed hip or knee flexion contracture, fixed plantarflexion contracture, significant spasticity, leg length discrepancy greater than 3 inches (8cm), valgus or varus deformity greater than 10 degrees and excessive body weight (>220ibs) Persons with cognitive impairment may not be able to comprehend how to safely use or maintain a SC-KAFO, SC options must be used with caution when cognitive ability and judgment are impaired. ',
    ],
    videoUrl: 'https://youtu.be/ySOhsVs0300',
  ),
  Meal(
    id: 'm16',
    categories: [
      'c3',
    ],
    title: 'Scott craig (Double bar) and single KAFO:',
    imageUrl: 'assets/images/m16.png',
    steps: [
      'Scott craig is useful for patients with paraplegia due to spinal cord injury.',
      '•Dis advantages:',
      '⁃Heavy',
      '⁃Less cosmetic',
      '⁃Fewer contact points reduce control.',
      '⁃Must be attached by shoes',
      '• Advanced:',
      ' Accommodate volume fluctuations',
      '⁃Highest material strength',
      '⁃Various knee joint are available',
      '⁃Most durable',
      '• Indications:',
      '⁃When maximum strength and durability are needed.',
      '⁃For individuals with uncontrolled or fluctuating edema (congestive heart failure, dialysis)',
      '• Contraindications:',
      '⁃When issues of energy expenditure make weight of the orthosis a factor.',
      '⁃When control of transverse plane motion is important',
    ],
    videoUrl: 'https://youtu.be/86b4TeNRrs0',
  ),
  Meal(
    id: 'm17',
    categories: [
      'c3',
    ],
    title: 'Thermoplastic KAFOs',
    imageUrl: 'assets/images/m17.png',
    steps: [
      "A molded thermoplastic KAFO (also known as hybrid thermoplastic and metal orthosis) is designed to have an intimate fit so that it can be worn under clothing and fits within the patient's shoe.",
      'The distal component (a SAFO or an HAFO) and the proximal component',
      'often encases the thigh from greater trochanter to femoral condyles and is',
      'closed with a pair of anterior Velcro straps. Orthotic knee joints and metal',
      'uprights (sidebars) connect the proximal and distal shells. The intimate',
      'total contact fit of molded thermoplastic allows significantly more effective control of the limb. The forces necessary for stabilization of the limb are distributed over a large surface area, reducing the possibility of discomfort or skin irritation.',
      'Control of rotation is better accomplished with the total contact thermoplastic KAFO as compared with the double upright system of conventional KAFOs. However, this intimate fit is problematic for persons',
      'with medical conditions associated with fluctuating edema and changing limb volume (e.g., congestive heart failure, kidney dialysis), as well as those who cyclically gain and lose weight. Similar to most thermoplasticAFOs, the use of different pairs of shoes (as long as heel height is constant) can also occur with thermoplastic KAFOs.',
      '*Advantages of Thermonlastic Knee-Ankle-Foot Orthoses',
      '1. Lightweight',
      '2. Interchangeability of shoes',
      '3. Greater cosmesis worn under clothing.',
      '4. Various knee joints are available.',
      '*Disadvantages of Thermoplastic Knee-Ankle-Foot Orthoses:',
      '1. Can be (hot)to wear.',
      '*Indications',
      '1. Intimate/total contact fit makes maximum limb control possible',
      '2. When energy expenditure makes weight of the orthosis an issue',
      '3. When control of transverse plane motion is needed',
      '*Contraindications',
      '1. Intimacy of fit is difficult when the individual is significantly obese',
      '2. Intimacy of fit is compromised when the individual has uncontrolled or fluctuating edema.',
      'Thermoplastic KAFOs are custom made by first moulding heated plastic (thermoplastics) to a modified replica of the leg. They have become popularized as a lighter and more cosmetically appealing design option.',
      'This device may be suitable for individuals with:',
      'Poliomyelitis',
      'Spinal cord injury',
      'Peripheral nerve injury',
      'Severe knee osteoarthritis',
      'Multiple Sclerosis (MS)',
      'Trauma',
    ],
    videoUrl: 'https://youtu.be/AbkA8ECdkFo',
  ),
  Meal(
    id: 'm18',
    categories: [
      'c3',
    ],
    title: 'Carbon composite knee-ankle-foot orthoses.',
    imageUrl: 'assets/images/m18.png',
    steps: [
      'Carbon composite materials have begun to be used in place of thermoplastics in KAFOs for persons with residual impairment for whom fatigue is a major concern. On average, because carbon composite KAFOs (CC-KAFOs) are as much as 30% lighter in weight than other materials, the energy cost of walking with CC-KAFOs may be up to (10%) less. Advantages of CC-KAFOs include improved cosmetics, increased walking speed, improved kinetic characteristics of walking, and exceptional durability. It is important to note that the cost of CC-KAFO may be nearly double that of a custom-molded thermoplastic KAFO. This carbon composite knee-ankle-foot orthosis has an anterior proximal shell with a posterior mid-shell and uses a stance control knee unit and a foot component similar to that of a hinged ankle-foot orthosis.',
    ],
    videoUrl: 'https://youtu.be/L2SyDyLTDmU',
  ),
  Meal(
    id: 'm19',
    categories: [
      'c4',
    ],
    title: 'Double metal HKAFOs',
    imageUrl: 'assets/images/m19.png',
    steps: [
      'Indications',
      'Double-sided COMPLEX orthosis should be used in case of:',
      'a)	flaccid paraparesis;',
      'b)	myelocytic, hydro myelomeningocele;',
      'c)	spinal muscular atrophy;',
      'd)	muscular dystrophy / myodystrophy with upper limbs mobility.',
    ],
    videoUrl: 'https://youtu.be/x19IV-UMfvM',
  ),
  Meal(
    id: 'm20',
    categories: [
      'c4',
    ],
    title: 'Single bar metal HKAFOs ',
    imageUrl: 'assets/images/m20.png',
    steps: [
      'used for persons with neuromuscular or musculoskeletal impairment affecting one lower extremity.',
    ],
    videoUrl: 'https://youtu.be/bbGdVHn-z8o',
  ),
  Meal(
    id: 'm21',
    categories: [
      'c4',
    ],
    title: 'thermoplastic HKAFOS ',
    imageUrl: 'assets/images/m21.png',
    steps: [
      "The light weight of this orthosis needs low energy of ambulation than conventional HKAFOS so it's significant and often functionally prohibitive",
      'This brace can support patients suffering from severe degenerative arthritis, joint instability, foot drop, and trauma',
    ],
    videoUrl: 'https://youtu.be/x19IV-UMfvM',
  ),
  Meal(
    id: 'm22',
    categories: [
      'c4',
    ],
    title: 'Reciprocating HKAFOs',
    imageUrl: 'assets/images/m22.png',
    steps: [
      'Mechanical linkage to couple flexion of one hip with extension of the other hip which permits a reciprocal step overstep gait as well as the option to swing to or swing through. It can be used for a variety of pathologies that result in paraplegia including spinal cord injury. This orthosis may be require time and effort so need training time about 45 to 80 hours over period of weeks to months. Using this device need stretching protocol for lower limb to ensure sufficient ROM in hip, knee and ankle. This orthosis also needs muscle strength, trunk and upper limb control to work efficiently.',
    ],
    videoUrl: 'https://youtu.be/TrIBMpd6dH4',
  ),
  Meal(
    id: 'm23',
    categories: [
      'c4',
    ],
    title: 'Hip orthosis',
    imageUrl: 'assets/images/m23.png',
    steps: [
      "This orthosis is prefabricated, or custom made to a patient's measurements. It provide support and control for individuals with hip disorders and after hip surgeries. It can control hip abduction, adduction, flexion, extension and rotation. HOs used to position femoral head in the acetabulum to allow for healing or to prevent further damage to the joint.",
      'Indications of HOs:',
      '1-hip replacement',
      '2-hip dislocation',
      '3-hip dysplasia',
    ],
    videoUrl: 'https://youtu.be/XGn9oEKKugQ',
  ),
  Meal(
    id: 'm24',
    categories: [
      'c5',
    ],
    title: 'Soft cervical orthosis (foam collar)',
    imageUrl: 'assets/images/m24.png',
    steps: [
      "Primary function of this orthosis is to limit exaggerated neck movements, but it provides little stability to cervical spine up to 10% restriction to cervical motion in all planes. It can be used for postoperative cervical spine in case of stable spine about 16 hours daily in the first week, 8 hours daily in the second week. It is contraindicated to use in whiplash injury and in neck pain because it causes muscles weakness.",
    ],
    videoUrl: 'https://youtu.be/eioqpIqqXlo',
  ),
  Meal(
    id: 'm25',
    categories: [
      'c5',
    ],
    title: 'Miami J collar',
    imageUrl: 'assets/images/m25.png',
    steps: [
      'Indications',
      'a)	lower cervical and upper thoracic pain/instability.',
      'b)	poor trunk control.',
      'c)	osteoporosis.',
      'd)	lower cervical sprains and strains.',
      'DESCRIPTION',
      'Spinal brace designed to support, stabilise and immobilise the cervical spine C2-C5 and upper thoracic at levels C6:T5. A longer-term management option to the Philadelphia collar. Breathable and antibacterial foam-lined collar (removable for hygiene purposes). Bivalved anterior/posterior semi-rigid shells.',
      'Multiple size options in pediatric and adult sizes.',
    ],
    videoUrl: 'https://youtu.be/cDrU9x9Z790',
  ),
  Meal(
    id: 'm26',
    categories: [
      'c5',
    ],
    title: 'The rigid collars',
    imageUrl: 'assets/images/m26.png',
    steps: [
      'are a similar design to the soft collars but are constructed out of plexiglass. They are easily applied and are easy to keep clean, an advantage of the plastic collar. This type of collar is also supplied in different sizes to fit the patient. These collars restrict motion in flexion and extension.[5] They not only support the chin but also the occiput, reducing active extension, especially in the end phase. A drawback of the rigid collars is that they potentially can cause venous outflow obstruction, which may elevate intracranial pressure.[6][7] If there is clear evidence of an increased intracranial pressure, the collar should be removed or re-positioned.',
    ],
    videoUrl: ' https://youtu.be/kVMuj_LpDJo',
  ),
  Meal(
    id: 'm27',
    categories: [
      'c5',
    ],
    title: 'posterior style orthosis',
    imageUrl: 'assets/images/m27.png',
    steps: [
      'two poster and four poster designs of cervical orthosis are more rigid immobilization of the cervical spine because of occipital pad. mandibular pad and sternal and thoracic pads',
    ],
    videoUrl: 'https://youtu.be/IyTbYQihjCc',
  ),
  Meal(
    id: 'm28',
    categories: [
      'c5',
    ],
    title: 'Halo brace',
    imageUrl: 'assets/images/m28.png',
    steps: [
      ' is an extensive brace which is surgically applied. It is a 4-post brace that is attached by pins which are placed in the cranial table with a jacket fitted to the torso.[1] Indications for a halo fixated brace range from:',
      'pre-surgical correction to post-operative fusion support. Additionally, a halo brace can be used as an alternative to surgery to conserve neck mobility.[4] The halo brace is more efficacious than a hard collar at limiting motion in the upper Movement / function limitations Flexion / extension limited by 96%, Lateral bending is limited by 96%, Rotation is limited by 99%. It offers maximum motion control to T3 and level cervical spine.',
    ],
    videoUrl: 'https://youtu.be/yV1qfTCQiQY',
  ),
  Meal(
    id: 'm29',
    categories: [
      'c6',
    ],
    title: 'SOMI Brace (Sternal Occipital Mandibular Immobilizer)',
    imageUrl: 'assets/images/m29.png',
    steps: [
      'Indications',
      'a)	Atlantoaxial instability caused by rheumatoid arthritis',
      'b)	Neural arch fractures of C2, because flexion causes instability',
      '• Contraindications.',
      'a)	The SOMI controls extension less effectively than do other orthoses.',
      'b)	Flexion and extension control at C3-T1: better served with a Minerva ',
    ],
    videoUrl: 'https://youtu.be/_U3tqlwemBw',
  ),
  Meal(
    id: 'm30',
    categories: [
      'c6',
    ],
    title: 'The Minerva orthosis',
    imageUrl: 'assets/images/m30.png',
    steps: [
      ' is a removable version of the Halo. This type of orthosis is offered to compliant patients who will not just remove the brace',
      'Introduction:',
      '1)	Mid-to-lower cervical spine injuries',
      '2)	Stable upper cervical spine injuries',
      '3)	Can be used with skull fractures when a Halo Fixator is contraindicated Children due to its decreased weight and increased comfort Movement / function limitations Flexion / extension limited by ~96%, Lateral bending is limited by ~96%and Rotation is limited by ~99%',
      '4)	This brace offers control of motion down to T3 level',
    ],
    videoUrl: 'https://youtu.be/QYub7VFQoLk',
  ),
  Meal(
    id: 'm31',
    categories: [
      'c7',
    ],
    title: 'CASH brace',
    imageUrl: 'assets/images/m31.png',
    steps: [
      'Cruciform Anterior Spinal Hyperextension (CASH) brace is strapped round the thoracolumbar region. Featuring pads to support the sternal and pelvic area, the cross-shaped bar can be adjusted according to the user.',
      'Following are some benefits of using this product:',
      'a)	It is used to immobilize the thoracic and lumbar region in case of vertebral fractures.',
      'b)	The support offered by the CASH brace promotes healing.',
      'c)	Patients suffering from osteoporosis can benefit from reduction of kyphosis by using this brace.',
      'd)	It helps in relieving pressure around the chest area.',
      'Contraindications:',
      'a)	Three-column spinal fractures involving anterior, middle, and posterior spinal structures Compression fractures caused by osteoporosis',
      'b)	 Ineffective in limiting scoliosis.',
    ],
    videoUrl: 'https://youtu.be/QlVafNgey2I',
  ),
  Meal(
    id: 'm32',
    categories: [
      'c7',
    ],
    title: 'Jewett brace ',
    imageUrl: 'assets/images/m32.png',
    steps: [
      'The Jewett brace is designed to give support to your thoracic and lumbar spine by preventing twisting and flexion (bending forward). It will also keep your back in the correct position while you are healing from your injury and/or surgery. Used for T11, T12 or L1 compression fracture Most people wear the brace between 6 to12 weeks. Activities to avoid while wearing your brace flexion, twisting or turning of your body driving a motor vehicle physical sport or running heavy lifting or manual work. Jewett and cash orthoses are contraindicated for potentially unstable fractures or burst fracture and contraindicated in patients with sternal fractures or an inability to tolerate direct pressure from the posterior pad.',
    ],
    videoUrl: 'https://youtu.be/O0jk9IQCAYA',
  ),
  Meal(
    id: 'm33',
    categories: [
      'c7',
    ],
    title: '(TLSO) Back Brace) body jacket)',
    imageUrl: 'assets/images/m33.png',
    steps: [
      'There are several back conditions for which a thoracolumbosacral orthosis (TLSO) can be helpful. TLSO refers to the region of the back these braces support, including the thoracic, lumbar and sacrum part of the spine. It also refers to the area where the thoracic and lumbar sections meet, which is known as the thoracolumbar region. TLSO body jacket can be used to manage fractures from T6 to L4.  TLSO braces are used to put pressure on unnatural curves that an individual may have, it then slows down the growth to eliminate the progress of the curve. These braces are used if you are diagnosed with a spinal disorder, deformity, or a different problem that needs structural support. If you are looking for an upper back brace for your specific condition such a kyphosis, osteoporosis, scoliosis, herniated disc, or a spinal fracture Bracing is recommended for children and adolescents TLSO braces are mainly recommended for adolescents between the ages of 12 and 15 whose Cobb angle measurements are between 20 and 40 degrees.',
    ],
    videoUrl: 'https://youtu.be/uHSl2y1dIms',
  ),
  //35 bec 34 after 15
  Meal(
    id: 'm35',
    categories: [
      'c8',
    ],
    title: 'Rigid LSO',
    imageUrl: 'assets/images/m35.png',
    steps: [
      'restrict the movement of the torso. It is used to treat a variety of conditions, from compression fractures to laminectomies, and is usually prescribed for use after surgery.',
      'wearing orthosis during the most challenging postural task (i.e., blindfolded while standing on a foam surface) significantly reduce postural sway parameters related to the position and displacement of the center of pressure . However, the use of this device had no significant effect on COP velocity.',
    ],
    videoUrl: 'https://youtu.be/ItcCV96XHgo',
  ),
  Meal(
    id: 'm36',
    categories: [
      'c8',
    ],
    title: 'Lumbosacral corset',
    imageUrl: 'assets/images/m36.png',
    steps: [
      'Lumbosacral corset is a spinal support widely used for patients suffering from low back pain due to various conditions.',
      "A lumbar corset works by putting pressure on your abdomen. This takes weight off your spine and joints to help you heal more easily. You may need a lumbar corset if you have low back pain, arthritis, or a degenerative disc disease. A corset can also be used for a short time to treat pain from a sprain or strain. A corset may also be used to stabilize your spine after a fracture or surgery. The corset will remind you not to move in certain directions, or to move more slowly. This will prevent you from moving quickly and causing more injury.",
    ],
    videoUrl: 'https://youtu.be/lWDqmvL9RCA',
  ),
  Meal(
    id: 'm37',
    categories: [
      'c9',
    ],
    title: 'Pelvic belt',
    imageUrl: 'assets/images/m37.jpg',
    steps: [
      "pelvic belts are popular among these women as a tool to prevent changes in pelvic alignment in addition to reduce lumbopelvic pain.The pelvic belt helps to stabilize the pelvis and is thought to be effective for relieving lumbar and pelvic pain.",
    ],
    videoUrl: 'https://youtu.be/mHJloZesUUE',
  ),
  Meal(
    id: 'm38',
    categories: [
      'c10',
    ],
    title: 'Milwaukee brace (Rigid CTLSO)',
    imageUrl: 'assets/images/m38.png',
    steps: [
      "Indications:",
      "Stabilize and prevent progression of a deformity in the spine",
      "Reduce lumbar lordosis",
      "Control scoliosis in an effort to prevent or delay surgery",
      "Help with the treatment of Scheuerman disease It remains the most effective brace for upper thoracic curves",
      "If the spinal curve has a Cobb angle between 20° and 40°, it is an indication to use a brace. Under this Cobb angle interval, the curve of the patient stays under observation. Above this interval surgeons will intervene rather than wear a brace",
      "Contraindications:",
      "Skeletally mature patients with a postural disorder (it will have no effect) Patients with a curvature over 40°",
      "Can’t be used in thoracic lordosis Lower thoracic and lumbar curves",
      "How to use",
      "For patients with more than one curve, the curve of greatest mechanical stiffness or primary curve should be loaded",
      "The brace is normally prescribed for children, with a postural disorder, who have not reached their growth spurt or who are in their fast growing period",
      "This style is considered a full-time brace and should be worn 23 hours a day",
    ],
    videoUrl: 'https://youtu.be/J5GD3CMe4Gc',
  ),
  Meal(
    id: 'm39',
    categories: [
      'c11',
    ],
    title: 'Boston ThoracolumbosacralOrthosis(Low profile TLSO)',
    imageUrl: 'assets/images/m39.jpg',
    steps: [
      'Indications',
      'Allow non-operative treatment of adolescents with idiopathic scoliosis Prevent progression of scoliosis in the growing child',
      'Most prevalent type of orthosis used and has equivalent results when compared with Milwaukee brace with the possible exception of use for high thoracic curves',
      'More comfortable and well tolerated',
      'Contraindications',
      'Severe thoracic lordosis',
      'Persistent worsening of hypokyphosis or thoracic lordosis while in brace treatment',
      'Major psychological reaction to the brace Massive obesity',
      'The inability of the patient to actively shift the trunk away from the lateral padsHow to use',
      'The brace is typically worn full-time (18 to 23 hours per day) to minimize the risk of curve progression',
      ],
    videoUrl: 'https://youtu.be/YsFVn0QJdj0',
  ),
  Meal(
    id: 'm40',
    categories: [
      'c12',
    ],
    title: 'Shoulder sling',
    imageUrl: 'assets/images/m40.jpg',
    steps: [
      'Indications',
      'Restrict shoulder motion as in dislocated or sublaxated shoulder Keep the humeral head in the glenoid cavity',
      'Immobilization of shoulder in case of humeral fractures.',
    ],
    videoUrl: 'https://youtu.be/NxZ4QHoU1K0',
  ),
  Meal(
    id: 'm41',
    categories: [
      'c12',
    ],
    title: 'Shoulder arm sling/arm sling',
    imageUrl: 'assets/images/m41.jpg',
    steps: [
      "An arm sling helps realign scapular symmetry and support the forearm in a flexed arm position. Usually, a splint, brace, or cast is first applied to the injured arm before using an arm sling. Arm slings are used to alleviate pain caused by a strain, surgery, dislocation, fracture, or injury in the shoulder, arm, elbow, or wrist in adults and children. An arm sling is very easy to wear and adjust and has shoulder straps with pads and a thumb loop. The lightweight fabric used for its production is a breathable blend of nylon, polyester, and cotton mesh fabric which permits the users to feel relaxed in the parts used. Different types of arm slings are helpful for different injuries like fracture, sprain, strain, or dislocation due to an accident. Physicians suggest an appropriate arm sling for a particular condition. Hwang and An (2015) reported improvements in walking velocity with the use of elastic arm sling and found it useful for gait training for stroke patients.",
      "DEVICE DESCRIPTION/IMPORTANT FEATURES:",
      "A shoulder immobilizer is a soft foam support consisting of four parts: large chest strap, upper arm cuff/strap, hand/wrist cuff/strap, and shoulder strap. The thumb loop provides support and stability for the arm and shoulder. The front-facing buckle allows the user to tighten or loosen the sling by adjusting the length of the sling straps. Arm sling is reversible for use on the left or right arm, Le., the wearer can use it on both arms as per his/her requirements. Minimum and maximum lengths of the strap are around 17 and 34 inches respectively, and the sling itself is 16 inches long. Since it is latex-free, the users do not feel any allergic reactions after use. An elastic arm sling consists of four plastic rings made of thin, flexible polyethene and three elastic bandages. Four plastic rings improve the arm position of the affected arm and provide shoulder stability without the complete restriction of the arm motion",
      "PURPOSE/HOW TO USE:",
      '1: Place arm in a sling and pull rings together.',
      '2: Hold the arm close to the body, keeping the elbow at 90.',
      '3: Pull the shoulder strap through the double rings and secure.',
      '4: Bring waist strap around',
      'INDICATIONS',
      '(1) Post-op impingement syndrome',
      '(2) Rotator cuff rupture repair',
      '(3) Manipulation of the frozen shoulder under anesthesia',
      '(4) Shoulder endoprothesis',
      '(5) Shoulder injuries',
      '(6) Subacromial and subcoracoid bursitis',
      '(7)  Shoulder dislocation – subluxation',
      '(8) Post-op protection and stabilization purposes',
      '(9) Prevents edema formation on distal, in cases of fracture',
      '(10) Hemiplegic shoulder',
    ],
    videoUrl: 'https://youtu.be/6LdIGE7zh4A',
  ),
  Meal(
    id: 'm42',
    categories: [
      'c12',
    ],
    title: 'Figure of eight harness clavicular brace',
    imageUrl: 'assets/images/m42.jpg',
    steps: [
      '((A)) DEVICE DESCRIPTION/IMPORTANT FEATURES:',
      'It has a designed eva support as anatomically that supporting the posture. The shoulder straps provide ease of use that produced from breathable and sponge fabric. The shoulder straps provide to be back away by passing under the armpits, and provide maximum postural support. It can be worn under clothing easily.',
      'The figure-of-eight bandage will be used for 4 weeks, and every week the participants will return for checking and adjusting the immobilisations. In this way, the dominant arm can remain free and simple activities will be allowed (writing, keyboarding and other). Participants and relatives of participants will also be educated on how to tighten the bandage when necessary. The figure-of-eight bandage should be adjusted so that the shoulder is pressed back in an arched position, almost like a back-stretch.',
      'The figure-of-eight should be used all day (including bath-time and bed-time); participants will be instructed not to remove the immobilisations. Patients will be instructed on how to properly wear and adjust the immobilisations should they slacken or be removed from the shoulders.',
      '((B)) PURPOSE/HOW TO USE:',
      '1: Place arms through arm straps so that the felt pad is located on the back and the foam insert is placed between the shoulder blades',
      '2: Adjust by pulling the arm straps tight. Fasten the contact closures on the arm pad',
      '3: The cushioned arm pad should be adjusted so that it fits under the arm and in front of the shoulder. The straps should be tight enough to pull the shoulders back',
      '4: A sponge bath or a tub bath will be recommended. Patients will also be advised that during the night a rolled up towel can be placed on the bed between their shoulder blades. This helps to keep the shoulder in the correct position while asleep',
      '((C)) INDICATIONS:',
      '1. Posture disorders',
      '2. Weakness of back and shoulder muscles',
      '3. Upright  posture support',
      '4. Clavicle fractures',
      '5. Clavicle and sterno-clavicle fracture half-fracture',

    ],
    videoUrl: 'https://youtu.be/ozkokLzUkOU',
  ),
  Meal(
    id: 'm43',
    categories: [
      'c12',
    ],
    title: 'SHOULDER ABDUCTION ORTHOSIS',
    imageUrl: 'assets/images/m43.jpg',
    steps: [
      "It's Soft and comfortable with a design which fits perfectly to the anatomy Consists of a cushion with a base that allows a 30° angle of abduction.",
      "Effects",
      "Immobilization of the shoulder and elbow joint. Indications Post-surgical treatments of the shoulder, post-reconstruction of rotator cuff injury and anteroposterior capsule reconstruction.Shoulderprosthesis. Fractures of the head of the humerus. Post-arthroscopy of the shoulder",

    ],
    videoUrl: 'https://youtu.be/ytTg7KPuNwM',
  ),
  Meal(
    id: 'm44',
    categories: [
      'c13',
    ],
    title: 'Elbow Orthoses (EO)',
    imageUrl: 'assets/images/m44.jpg',
    steps: [
      'These braces cross the elbow and can be used to resist movement or assist bending of the elbow for progressive stretching. EOs can also be used for support and positioning. These devices may be suitable for individuals with: Soft tissue injuries including ligamentous injuries.',
      "Elbow orthosis",
      "1 The forearm support band or counterforce brace",
      "it's a common splint prescribed for lateral epicondylitis",
    ],
    videoUrl: 'https://youtu.be/YzE80L-QJZQ',
  ),
  Meal(
    id: 'm45',
    categories: [
      'c13',
    ],
    title: 'Cubital tunnel splint',
    imageUrl: 'assets/images/m45.jpg',
    steps: [
      "Cubital tunnel splint Its indicated in cases of cubital tunnel syndrome (Ulnar nerve compression at the medial elbow is known as cubital tunnel syndrome)",
      "Full elbow extension allows for the least amount of pressure on the ulnar nerve: however, most patients will not be able to tolerate immobilization in full extension. Therefore, a custom splint should be fit with the elbow in comfortable extension, anywhere between 30 and 60 degrees of flexion",
    ],
    videoUrl: 'https://youtu.be/7I6ZOGMkko8',
  ),
  Meal(
    id: 'm46',
    categories: [
      'c14',
    ],
    title: 'Resting hand orthosis',
    imageUrl: 'assets/images/m46.jpg',
    steps: [
      "It may be volar based or dorsal based or Cirumferential The purpose of a hand splint is to:",
      "1. properly position and protect the affected hand",
      "2. protect the joints and prevent contractures",
      "3. decrease risk of swelling",
      "It have two form resting hand splint  restinghand splint with finger separators",
    ],
    videoUrl: 'https://youtu.be/wZHC60l-BGQ',
  ),
  Meal(
    id: 'm47',
    categories: [
      'c14',
    ],
    title: 'Cock-up splint',
    imageUrl: 'assets/images/m47.jpg',
    steps: [
      "helps to immobilise radio carpal joint providing rest and stability and allowing reduction of inflammation and pain . It also protect the extensor tendons.",
      "Volar splint may used to stabilize wrist after carpal tunnel release preventing median nerve and flexor tendon",

    ],
    videoUrl: 'https://youtu.be/YhPPeDNO1K0',
  ),
  Meal(
    id: 'm48',
    categories: [
      'c14',
    ],
    title: 'Dynamic wrist extension splints',
    imageUrl: 'assets/images/m48.jpg',
    steps: [
      "Dynamic wrist extension splints substitute for wrist extension while allowing free finger's motion.",
      "They're thermoplastic splints, made of mouldable plastic, adjusted and fitted perfectly to a part of your limb",
      "They're used during the day to maintain joint alignment, assist extension, and provide controlled flexion for 3 to 4 weeks after surgery",
      "Indication:",
      "-Radial Nerve Palsy or wrist drop",
      "-Extensor tendon injuries/repairs",
      "-Stoke patients with limited wrist extension and active digit flexion",
      "-Patients with contracted wrists and active digit flexion",
      "-Injuries requiring limited active range of motion",
    ],
    videoUrl: 'https://youtu.be/_o0g3pkcldw',
  ),
  Meal(
    id: 'm49',
    categories: [
      'c14',
    ],
    title: 'Thermoplastic tenodesis orthosis',
    imageUrl: 'assets/images/m49.jpg',
    steps: [
      "-It is critical to gain tenodesis function to enable task performance .it does not require active movement of the fingers. By simply moving the wrist up and down, passive grasp and release can be performed.",
      "-promoting correct tension in muscles and reducing spasticity that may impact the balance and function of the hand.",
      "-prevention of oedema in the hand.",
      "Indication:",
      "_Tenodesis orthosis is ideal for spinal cord injury patients as C6 quadriplegic patients",
      "_ It is used to facilitate grasp in people with tetraplegia who have wrist extension against gravity but no active finger function (C6 Motor Level).",

    ],
    videoUrl: 'https://youtu.be/_jOSSw6R1_w ',
  ),
  Meal(
    id: 'm50',
    categories: [
      'c14',
    ],
    title: 'Rom stop finger splints',
    imageUrl: 'assets/images/m50.png',
    steps: [
      "ROM-Stops Finger Splint Replacement Parts is used to block finger flexion or extension at various increments without slippage.",
      "It is easy to individualize the degrees of motion for each finger by using different length ROM-Stops.",
      "Indication:",
      "It is ideal for MP joint arthroplasty, PIP joint arthroplasty or extensor tendon lacerations.",
      "Types:",
      "1- Dorsal based wrist orthoses dynamic motion block orthoses with outriggers.",
      "2- Volar based wrist orthoses dynamic motion block orthoses with outriggers.",
    ],
    videoUrl: 'https://youtu.be/Nx_c9QtC1Zg',
  ),
  Meal(
    id: 'm51',
    categories: [
      'c15',
    ],
    title: 'Thumb splints(hand based,forearm based)',
    imageUrl: 'assets/images/m51.png',
    steps: [
      " keep the thumb immobilized while still allowing the fingers to move and support joints that are painful or unstable due to arthritis or soft tissue injury. It improve the function of the hand.",
      "Forearm base  use in cases as decorvan syndrome,  acute phase of rheumatoid arthritis",
    ],
    videoUrl: 'https://youtu.be/N115-4u3oGw',
  ),
  Meal(
    id: 'm52',
    categories: [
      'c16',
    ],
    title: 'Finger Splints',
    imageUrl: 'assets/images/m52.jpg',
    steps: [
      "that block hyperextension without limiting flexion are often very successful long-term solutions in patients with mild to moderate Swan Neck Deformity. These comfortable, unobtrusive splints keep the finger in proper alignment and prevent hyperextension at the PIP joint.",

    ],
    videoUrl: 'https://youtu.be/AIlbYyyuW4U',
  ),
  Meal(
    id: 'm53',
    categories: [
      'c16',
    ],
    title: 'Aluminum Foam Splints',
    imageUrl: 'assets/images/m53.jpg',
    steps: [
      "An aluminum foam splint is a highly adaptive splint that can be rolled folded or formed into almost any application with the use of a quality support bandage. Available in a rolled or flat form, shrink-wrapped for protection.",
      "Indications for use of the ActimoveAlufoam Aluminium Finger Splint:",
      "Subungual haematoma",
      "Nail bed laceration",
      "Distal phalanx fracture",
      "Mallet finger",
      "Flexor digitorum profundus (FDP) avulsion",
      "Distal interphalangeal (DIP) joint dislocations",
      "Finger injuries",
      "Benefits and design features of the ActimoveAlufoam Aluminium Finger Splint:",
      "Lightweight and strong",
      "Flexible aluminium",
      "Easily moulded and cut to ensure patient comfort",
      "Reliable stabilisation",
      "High density foam padding",
      "Protects injuries",
      "Adjusts as swelling subsides",
      "Range of widths",
    ],
    videoUrl: 'https://youtu.be/f3M0h9nhV54',
  ),
  Meal(
    id: 'm54',
    categories: [
      'c16',
    ],
    title: 'Tripoint finger splint',
    imageUrl: 'assets/images/m54.jpg',
    steps: [
      "is positioned for correction of a boutonnie 're deformity.Holds the PIPJ in neutral extension.The splint creates pressure to straighten and immobilize the finger.",
    ],
    videoUrl: 'https://youtu.be/KkKhQbjtmeI',
  ),
  Meal(
    id: 'm55',
    categories: [
      'c16',
    ],
    title: 'Ulner deviation orthosis',
    imageUrl: 'assets/images/m55.jpg',
    steps: [
      "This splint design can be used to improve the alignment of strongly deviated fingers, which is in many cases caused by rheumatoid arthritis. An ulnar drift deformity is characterized by ulnar deviation and volar subluxation of the metacarpal phalangeal (MCP) joints. In rheumatoid arthritis, chronic inflammation of the MCP joints and many other contributing factors cause damage to the joint capsule and surrounding ligaments resulting in this deformity .The ulnar deviation orthosis provides support to the MP join which restricts flexion and may assist in proper alignment by pulling the fingers radially out of ulnar deviation.",
    ],
    videoUrl: 'https://youtu.be/jaox7iWIuAc',
  ),
  Meal(
    id: 'm56',
    categories: [
      'c17',
    ],
    title: 'Mallet finger orthosis',
    imageUrl: 'assets/images/m56.jpg',
    steps: [
      "The main goal of an orthosis for the mallet finger is to maintain the DIP finger joint in passive (or slight hyper) extension so that healing of the injured tissue takes place. The orthosis should allow functional flexion of the Proximal Inter-Phalangeal (PIP) joint. This orthotic intervention promotes tendon healing without the formation of adhesions, resulting in a strong tendon that is able to pull through its full excursion .the patient should wear the mallet orthosis fulltime for a period of 6-8 weeks and may need to continue this with 4-6 weeks of night use as well.",
    ],
    videoUrl: 'https://youtu.be/YAX17L6IUu4',
  ),
];
