import 'package:flutter/material.dart';

import '../widgets/custom_rich_text.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.fromLTRB(15, 35, 15, 5),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Align(
                alignment: Alignment.center,
                child: Text(
                  'Privacy Policy',
                  style: TextStyle(
                    color: Colors.black,
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
              ),
              SizedBox(
                height: 10,
              ),
              CustomRichText(
                mainText: 'Orthosis Guide ',
                subText:
                    'is committed to protecting your privacy. This privacy policy applies to our application named Orthosis Guide, and it is associated subdomains (collectively our “Service”). By accessing or using our Service, you signify that you have read, understood and agreed to our Privacy Policy and our Terms of Service.',
              ),
              Text(
                'Definitions and key terms for this Privacy Policy',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              CustomRichText(
                mainText: 'Cookie: ',
                subText:
                    'small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.',
              ),
              CustomRichText(
                mainText: 'We: ',
                subText:
                    'when this policy mentions “we,” “us,” or “our,” it refers to Orthosis Guide that is responsible for your information under this Privacy Policy.',
              ),
              CustomRichText(
                mainText: 'Country: ',
                subText:
                    'where Orthosis Guide or the owners/founders of Orthosis Guide are based, in this case is Egypt.',
              ),
              CustomRichText(
                mainText: 'Customer: ',
                subText:
                    'refers to the person that uses the Orthosis Guide Service.',
              ),
              CustomRichText(
                mainText: 'Device: ',
                subText:
                    'any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Orthosis Guide and use the services.',
              ),
              CustomRichText(
                mainText: 'IP address: ',
                subText:
                    'Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.',
              ),
              CustomRichText(
                mainText: 'Personal Data: ',
                subText:
                    'any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.',
              ),
              CustomRichText(
                mainText: 'Service: ',
                subText:
                    'refers to the service provided by Orthosis Guide as described in the relative terms (if available) and on this platform.',
              ),
              CustomRichText(
                mainText: 'Third-party service: ',
                subText:
                    'refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.',
              ),
              CustomRichText(
                mainText: 'You: ',
                subText:
                    ' a person or entity that is registered with Orthosis Guide to use the Services.',
              ),
              Text(
                'Information automatically collected',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'There is some information like your Internet Protocol (IP) address and device characteristics — are collected automatically when you use our App. This information may be used to connect your device to the Internet.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                'Do we collect your personal data?',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'This application doesn’t collect any personal information or data from customers (ie. location, emails, phone number, etc)',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                'Governing Law',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'The laws of the Country, excluding its conflicts of law rules, shall govern this Agreement and your use of our service. Your use of our service may also be subject to other local, state, national, or international laws.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                'Do we use Cookies?',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'We don’t use cookies in our Service.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                'Links to Other Websites',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by Orthosis Guide. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                'Changes To Our Privacy Policy',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below. Last modification date; 2023-03-12',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                'Third-Party Services',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'We may provide links to third-party websites or services ("Third- Party Services").',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                'You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                'Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own responsibility and subject to such third parties terms and conditions.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                'Your Consent',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'By using our service, you consent to this Privacy Policy. If you don’t agree with this Privacy Policy, please don’t access, install or use Orthosis Guide.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Divider(
                color: Colors.black,
              ),
              Align(
                alignment: Alignment.center,
                child: Text(
                  'Disclaimer',
                  style: TextStyle(
                    color: Colors.black,
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                'No Advice',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'This app (Orthosis Guide) provides only information, is not medical or treatment advice and may not be treated as such by the user. As such, this App may not be relied upon for the purposes of medical diagnosis or as a recommendation for medical care or treatment. The information on this App is not a substitute for professional medical advice, diagnosis or treatment. All content, including text, graphics, images and information, contained on or available through this App is for general and educational information purposes only.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                'Professional Medical Advice and Assistance',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'You are strongly encouraged to confirm any information obtained from or through this App with your physician or another professional healthcare provider and to review all information regarding any medical condition or treatment with your physician or other a professional healthcare provider',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                'No Reliance',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'YOU MUST NEVER RELY ON ANY INFORMATION OBTAINED USING THIS APP FOR ANY DIAGNOSIS OR RECOMMENDATION FOR MEDICAL TREATMENT. YOU MUST NEVER RELY ON THE INFORMATION RECEIVED FROM THIS APP AS ALTERNATIVE TO MEDICAL ADVICE FROM YOUR PHYSICIAN OR OTHER PROFESSIONAL HEALTHCARE PROVIDER.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                'YOU MUST NEVER DISREGARD PROFESSIONAL MEDICAL ADVICE OR DELAY SEEKING MEDICAL TREATMENT AS RESULT OF ANY INFORMATION YOU HAVE SEEN ON OR ACCESSED THROUGH THIS APP. IF YOU HAVE ANY SPECIFIC QUESTIONS ABOUT ANY MEDICAL MATTER YOU SHOULD CONSULT YOUR PHYSICIAN OR OTHER PROFESSIONAL HEALTHCARE PROVIDER. IF YOU THINK YOU MAY BE SUFFERING FROM ANY MEDICAL CONDITION YOU SHOULD SEEK IMMEDIATE MEDICAL ATTENTION.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                'No Warranty',
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'The information provided by this App is provided “as is” without any representations or warranties, express or implied. Orthosis Guide makes no representations or warranties in relation to the medical or other information in this App.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                'Orthosis Guide does not warrant that:',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                '-The information provided by this App will be constantly available, or available at all;',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                'or',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                '-The information provided by this App is complete, true, accurate, up-to-date, or non-misleading.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                'Orthosis Guide IS NOT RESPONSIBLE OR LIABLE FOR ANY ADVICE, COURSE OF TREATMENT, DIAGNOSIS OR ANY OTHER INFORMATION, SERVICES OR PRODUCTS THAT YOU OBTAIN THROUGH THE USE OF THIS APP.',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              SizedBox(
                height: 10,
              ),
              Text(
                'By using the app, you have acknowledged that:',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                '-YOU HAVE READ AND UNDERSTAND THIS MEDICAL DISCLAIMER',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                '-YOU AGREE WITH THIS MEDICAL DISCLAIMER',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
              Text(
                ' -YOU AGREE TO BE LEGALLY BOUND BY THIS MEDICAL DISCLAIMER',
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
